import type { BenchCase } from "../types";

/**
 * AST-tier cases. These are the operations HashPilot claims as its top tier, so
 * they carry the strictest expectations: an edit either produces exactly the
 * named output or is refused.
 */
export const astCases: BenchCase[] = [
  {
    id: "ast-rename-ts-local",
    description: "rename a function and its call sites in TypeScript",
    file: "svc.ts",
    source: [
      "export function loadConfig(): string {",
      '  return "cfg";',
      "}",
      "",
      "export function main(): string {",
      "  return loadConfig();",
      "}",
      "",
    ].join("\n"),
    edit: { operation: "rename-symbol", oldName: "loadConfig", newName: "readConfig" },
    expected: [
      "export function readConfig(): string {",
      '  return "cfg";',
      "}",
      "",
      "export function main(): string {",
      "  return readConfig();",
      "}",
      "",
    ].join("\n"),
    tags: ["rename", "typescript"],
  },
  {
    id: "ast-rename-py-local",
    description: "rename a function and its call sites in Python",
    file: "svc.py",
    source: ["def load_config():", '    return "cfg"', "", "", "def main():", "    return load_config()", ""].join("\n"),
    edit: { operation: "rename-symbol", oldName: "load_config", newName: "read_config" },
    expected: ["def read_config():", '    return "cfg"', "", "", "def main():", "    return read_config()", ""].join("\n"),
    tags: ["rename", "python"],
  },
  {
    id: "ast-rename-go-local",
    description: "rename a function and its call sites in Go",
    file: "svc.go",
    source: [
      "package main",
      "",
      "func loadConfig() string {",
      '\treturn "cfg"',
      "}",
      "",
      "func main() {",
      "\t_ = loadConfig()",
      "}",
      "",
    ].join("\n"),
    edit: { operation: "rename-symbol", oldName: "loadConfig", newName: "readConfig" },
    expected: [
      "package main",
      "",
      "func readConfig() string {",
      '\treturn "cfg"',
      "}",
      "",
      "func main() {",
      "\t_ = readConfig()",
      "}",
      "",
    ].join("\n"),
    tags: ["rename", "go"],
  },
  {
    id: "ast-rename-absent-symbol",
    description: "renaming a symbol that does not exist must be refused, not silently applied",
    file: "svc.ts",
    source: ["export function a(): number {", "  return 1;", "}", ""].join("\n"),
    edit: { operation: "rename-symbol", oldName: "nosuch", newName: "other" },
    expectRefusal: "no such symbol; a no-op reported as success would let an agent believe a refactor landed",
    tags: ["rename", "typescript"],
  },
  {
    id: "ast-replace-body-ts",
    description: "replace a function body without disturbing the signature or neighbours",
    file: "svc.ts",
    source: [
      "export function pick(): string {",
      '  return "old";',
      "}",
      "",
      "export const after = 1;",
      "",
    ].join("\n"),
    // The body is supplied unindented: the AST tier owns indentation and
    // re-indents to the symbol's block level. Passing leading whitespace
    // double-indents the result.
    edit: { operation: "replace-body", symbolName: "pick", newBody: 'return "new";' },
    expected: [
      "export function pick(): string {",
      '  return "new";',
      "}",
      "",
      "export const after = 1;",
      "",
    ].join("\n"),
    tags: ["replace-body", "typescript"],
  },
  {
    id: "ast-insert-after-ts",
    description: "insert a declaration after a named symbol",
    file: "svc.ts",
    source: ["export function go(): number {", "  return 1;", "}", ""].join("\n"),
    edit: { operation: "insert-after", symbolName: "go", content: "export const AFTER = 1;" },
    expected: ["export function go(): number {", "  return 1;", "}", "export const AFTER = 1;", ""].join("\n"),
    tags: ["insert", "typescript"],
  },
  {
    id: "ast-add-import-merge-ts",
    description: "adding a name from an already-imported module must merge, not duplicate the module",
    file: "svc.ts",
    source: [
      'import { readFileSync } from "node:fs";',
      "",
      "export function go(): string {",
      '  return String(readFileSync("a"));',
      "}",
      "",
    ].join("\n"),
    edit: { operation: "add-import", importSpec: '{ writeFileSync } from "node:fs"' },
    expected: [
      'import { readFileSync, writeFileSync } from "node:fs";',
      "",
      "export function go(): string {",
      '  return String(readFileSync("a"));',
      "}",
      "",
    ].join("\n"),
    tags: ["import", "typescript", "grouped-import"],
  },
  {
    id: "ast-add-import-type-no-merge-ts",
    description: "a value import must not merge into `import type`, whose bindings are erased at compile time",
    file: "svc.ts",
    source: ['import type { Foo } from "./m";', "", "export const x = 1;", ""].join("\n"),
    edit: { operation: "add-import", importSpec: '{ bar } from "./m"' },
    expected: [
      'import type { Foo } from "./m";',
      'import { bar } from "./m";',
      "",
      "export const x = 1;",
      "",
    ].join("\n"),
    tags: ["import", "typescript", "type-import"],
  },
  {
    id: "ast-add-import-no-trailing-newline-ts",
    description: "inserting after a last import that ends at EOF must not glue both statements onto one line",
    file: "svc.ts",
    source: 'import { a } from "./a";',
    edit: { operation: "add-import", importSpec: '{ b } from "./b"' },
    // The encoding layer preserves the file's missing trailing newline, so the
    // guard here is only that the two statements land on separate lines.
    expected: ['import { a } from "./a";', 'import { b } from "./b";'].join("\n"),
    tags: ["import", "typescript"],
  },
  {
    id: "ast-remove-import-one-name-ts",
    description: "removing one name from a grouped import must leave the other bindings intact",
    file: "svc.ts",
    source: [
      'import { readFileSync, writeFileSync, statSync } from "node:fs";',
      "",
      "export function go(): void {",
      '  writeFileSync("a", String(readFileSync("b")));',
      "}",
      "",
    ].join("\n"),
    edit: { operation: "remove-import", importSpec: "statSync" },
    expected: [
      'import { readFileSync, writeFileSync } from "node:fs";',
      "",
      "export function go(): void {",
      '  writeFileSync("a", String(readFileSync("b")));',
      "}",
      "",
    ].join("\n"),
    tags: ["import", "typescript", "grouped-import"],
  },
  {
    id: "ast-refuse-broken-source",
    description: "a file that already has a syntax error must be refused rather than edited blind",
    file: "svc.ts",
    source: ["export function go(): number {", "  return 1;", ""].join("\n"),
    edit: { operation: "rename-symbol", oldName: "go", newName: "run" },
    expectRefusal: "source does not parse; the AST tier has no trustworthy tree to edit against",
    tags: ["parse-gate", "typescript"],
  },
  {
    id: "ast-rename-deep-nesting",
    description: "rename must reach a reference nested more than ten blocks deep",
    file: "deep.ts",
    source: (() => {
      const open = Array.from({ length: 14 }, (_, i) => "  ".repeat(i + 1) + `if (n > ${i}) {`);
      const close = Array.from({ length: 14 }, (_, i) => "  ".repeat(14 - i) + "}");
      return [
        "export function target(): number {",
        "  return 1;",
        "}",
        "",
        "export function caller(n: number): number {",
        ...open,
        "  ".repeat(15) + "return target();",
        ...close,
        "  return 0;",
        "}",
        "",
      ].join("\n");
    })(),
    edit: { operation: "rename-symbol", oldName: "target", newName: "renamed" },
    expected: (() => {
      const open = Array.from({ length: 14 }, (_, i) => "  ".repeat(i + 1) + `if (n > ${i}) {`);
      const close = Array.from({ length: 14 }, (_, i) => "  ".repeat(14 - i) + "}");
      return [
        "export function renamed(): number {",
        "  return 1;",
        "}",
        "",
        "export function caller(n: number): number {",
        ...open,
        "  ".repeat(15) + "return renamed();",
        ...close,
        "  return 0;",
        "}",
        "",
      ].join("\n");
    })(),
    knownIssue: 39,
    tags: ["rename", "typescript", "depth-cap"],
  },
];
