import type { BenchCase } from "../types";

/**
 * AST-tier cases. These are the operations HashPilot claims as its top tier, so
 * they carry the strictest expectations: an edit either produces exactly the
 * named output or is refused.
 */
export const astCases: BenchCase[] = [
  {
    id: "ast-rename-ts-local",
    description: "rename a function and its call sites in TypeScript",
    file: "svc.ts",
    source: [
      "export function loadConfig(): string {",
      '  return "cfg";',
      "}",
      "",
      "export function main(): string {",
      "  return loadConfig();",
      "}",
      "",
    ].join("\n"),
    edit: { operation: "rename-symbol", oldName: "loadConfig", newName: "readConfig" },
    expected: [
      "export function readConfig(): string {",
      '  return "cfg";',
      "}",
      "",
      "export function main(): string {",
      "  return readConfig();",
      "}",
      "",
    ].join("\n"),
    tags: ["rename", "typescript"],
  },
  {
    id: "ast-rename-py-local",
    description: "rename a function and its call sites in Python",
    file: "svc.py",
    source: ["def load_config():", '    return "cfg"', "", "", "def main():", "    return load_config()", ""].join("\n"),
    edit: { operation: "rename-symbol", oldName: "load_config", newName: "read_config" },
    expected: ["def read_config():", '    return "cfg"', "", "", "def main():", "    return read_config()", ""].join("\n"),
    tags: ["rename", "python"],
  },
  {
    id: "ast-rename-go-local",
    description: "rename a function and its call sites in Go",
    file: "svc.go",
    source: [
      "package main",
      "",
      "func loadConfig() string {",
      '\treturn "cfg"',
      "}",
      "",
      "func main() {",
      "\t_ = loadConfig()",
      "}",
      "",
    ].join("\n"),
    edit: { operation: "rename-symbol", oldName: "loadConfig", newName: "readConfig" },
    expected: [
      "package main",
      "",
      "func readConfig() string {",
      '\treturn "cfg"',
      "}",
      "",
      "func main() {",
      "\t_ = readConfig()",
      "}",
      "",
    ].join("\n"),
    tags: ["rename", "go"],
  },
  {
    id: "ast-rename-absent-symbol",
    description: "renaming a symbol that does not exist must be refused, not silently applied",
    file: "svc.ts",
    source: ["export function a(): number {", "  return 1;", "}", ""].join("\n"),
    edit: { operation: "rename-symbol", oldName: "nosuch", newName: "other" },
    expectRefusal: "no such symbol; a no-op reported as success would let an agent believe a refactor landed",
    tags: ["rename", "typescript"],
  },
  {
    id: "ast-replace-body-ts",
    description: "replace a function body without disturbing the signature or neighbours",
    file: "svc.ts",
    source: [
      "export function pick(): string {",
      '  return "old";',
      "}",
      "",
      "export const after = 1;",
      "",
    ].join("\n"),
    // The body is supplied unindented: the AST tier owns indentation and
    // re-indents to the symbol's block level. Passing leading whitespace
    // double-indents the result.
    edit: { operation: "replace-body", symbolName: "pick", newBody: 'return "new";' },
    expected: [
      "export function pick(): string {",
      '  return "new";',
      "}",
      "",
      "export const after = 1;",
      "",
    ].join("\n"),
    tags: ["replace-body", "typescript"],
  },
  {
    id: "ast-insert-after-ts",
    description: "insert a declaration after a named symbol",
    file: "svc.ts",
    source: ["export function go(): number {", "  return 1;", "}", ""].join("\n"),
    edit: { operation: "insert-after", symbolName: "go", content: "export const AFTER = 1;" },
    expected: ["export function go(): number {", "  return 1;", "}", "export const AFTER = 1;", ""].join("\n"),
    tags: ["insert", "typescript"],
  },
  {
    id: "ast-add-import-merge-ts",
    description: "adding a name from an already-imported module must merge, not duplicate the module",
    file: "svc.ts",
    source: [
      'import { readFileSync } from "node:fs";',
      "",
      "export function go(): string {",
      '  return String(readFileSync("a"));',
      "}",
      "",
    ].join("\n"),
    edit: { operation: "add-import", importSpec: '{ writeFileSync } from "node:fs"' },
    expected: [
      'import { readFileSync, writeFileSync } from "node:fs";',
      "",
      "export function go(): string {",
      '  return String(readFileSync("a"));',
      "}",
      "",
    ].join("\n"),
    tags: ["import", "typescript", "grouped-import"],
  },
  {
    id: "ast-add-import-type-no-merge-ts",
    description: "a value import must not merge into `import type`, whose bindings are erased at compile time",
    file: "svc.ts",
    source: ['import type { Foo } from "./m";', "", "export const x = 1;", ""].join("\n"),
    edit: { operation: "add-import", importSpec: '{ bar } from "./m"' },
    expected: [
      'import type { Foo } from "./m";',
      'import { bar } from "./m";',
      "",
      "export const x = 1;",
      "",
    ].join("\n"),
    tags: ["import", "typescript", "type-import"],
  },
  {
    id: "ast-add-import-no-trailing-newline-ts",
    description: "inserting after a last import that ends at EOF must not glue both statements onto one line",
    file: "svc.ts",
    source: 'import { a } from "./a";',
    edit: { operation: "add-import", importSpec: '{ b } from "./b"' },
    // The encoding layer preserves the file's missing trailing newline, so the
    // guard here is only that the two statements land on separate lines.
    expected: ['import { a } from "./a";', 'import { b } from "./b";'].join("\n"),
    tags: ["import", "typescript"],
  },
  {
    id: "ast-remove-import-one-name-ts",
    description: "removing one name from a grouped import must leave the other bindings intact",
    file: "svc.ts",
    source: [
      'import { readFileSync, writeFileSync, statSync } from "node:fs";',
      "",
      "export function go(): void {",
      '  writeFileSync("a", String(readFileSync("b")));',
      "}",
      "",
    ].join("\n"),
    edit: { operation: "remove-import", importSpec: "statSync" },
    expected: [
      'import { readFileSync, writeFileSync } from "node:fs";',
      "",
      "export function go(): void {",
      '  writeFileSync("a", String(readFileSync("b")));',
      "}",
      "",
    ].join("\n"),
    tags: ["import", "typescript", "grouped-import"],
  },
  {
    id: "ast-refuse-broken-source",
    description: "a file that already has a syntax error must be refused rather than edited blind",
    file: "svc.ts",
    source: ["export function go(): number {", "  return 1;", ""].join("\n"),
    edit: { operation: "rename-symbol", oldName: "go", newName: "run" },
    expectRefusal: "source does not parse; the AST tier has no trustworthy tree to edit against",
    tags: ["parse-gate", "typescript"],
  },
  {
    id: "ast-rename-deep-nesting",
    description: "rename must reach a reference nested more than ten blocks deep",
    file: "deep.ts",
    source: (() => {
      const open = Array.from({ length: 14 }, (_, i) => "  ".repeat(i + 1) + `if (n > ${i}) {`);
      const close = Array.from({ length: 14 }, (_, i) => "  ".repeat(14 - i) + "}");
      return [
        "export function target(): number {",
        "  return 1;",
        "}",
        "",
        "export function caller(n: number): number {",
        ...open,
        "  ".repeat(15) + "return target();",
        ...close,
        "  return 0;",
        "}",
        "",
      ].join("\n");
    })(),
    edit: { operation: "rename-symbol", oldName: "target", newName: "renamed" },
    expected: (() => {
      const open = Array.from({ length: 14 }, (_, i) => "  ".repeat(i + 1) + `if (n > ${i}) {`);
      const close = Array.from({ length: 14 }, (_, i) => "  ".repeat(14 - i) + "}");
      return [
        "export function renamed(): number {",
        "  return 1;",
        "}",
        "",
        "export function caller(n: number): number {",
        ...open,
        "  ".repeat(15) + "return renamed();",
        ...close,
        "  return 0;",
        "}",
        "",
      ].join("\n");
    })(),
    knownIssue: 39,
    tags: ["rename", "typescript", "depth-cap"],
  },
  {
    id: "dry-run-preview-is-a-diff",
    description: "A dry-run rename previews the hunk and leaves the file alone (#98)",
    file: "preview.ts",
    source: (() => [
      "export function target(): number {",
      ...Array.from({ length: 40 }, (_, i) => `  const filler${i} = ${i};`),
      "  return 1;",
      "}",
      "",
      "export const used = target();",
      "",
    ].join("\n"))(),
    edit: { operation: "rename-symbol", oldName: "target", newName: "renamed", dryRun: true },
    expectPreview: "diff",
    tags: ["rename", "typescript", "dry-run"],
  },
  {
    id: "dry-run-include-source-opt-in",
    description: "includeSource still returns the whole post-edit file on request (#98)",
    file: "preview.ts",
    source: (() => [
      "export function target(): number {",
      ...Array.from({ length: 40 }, (_, i) => `  const filler${i} = ${i};`),
      "  return 1;",
      "}",
      "",
      "export const used = target();",
      "",
    ].join("\n"))(),
    edit: { operation: "rename-symbol", oldName: "target", newName: "renamed", dryRun: true, includeSource: true },
    expectPreview: "source",
    tags: ["rename", "typescript", "dry-run"],
  },
  {
    id: "insert-after-parameter-name-refused",
    description: "a name that exists only as a parameter refuses instead of splicing into the parameter list",
    file: "handler.ts",
    source: 'function handler(config: string): void {\n  console.log(config);\n}\n',
    edit: { operation: "insert-after", symbolName: "config", content: "const injected = 1;" },
    expectRefusal: "the only match is a parameter: inserting a statement there produces a syntax error the tool reports as success (#38)",
    tags: ["insert-after", "typescript", "anchor", "38"],
  },
  {
    id: "insert-after-ambiguous-method-refused",
    description: "two methods with the same name refuse rather than picking the first",
    file: "twoclasses.ts",
    source: 'class A {\n  run() {}\n}\nclass B {\n  run() {}\n}\n',
    edit: { operation: "insert-after", symbolName: "run", content: "// note" },
    expectRefusal: "both classes define run: choosing one silently is the failure mode (#38)",
    tags: ["insert-after", "typescript", "ambiguity", "38"],
  },
  // ── JavaScript module systems (#139) ──────────────────────────────────
  // The suite had zero JavaScript cases while `ast_capabilities` advertised the
  // language, and that hole is exactly where #139 lived: `add-import` wrote ESM
  // syntax into CommonJS files, reported success, and left a file Node could not
  // load. The headline "0 silent corruption" was measuring a gap. These cases
  // close it — see #142 for the rest of the coverage work.
  {
    id: "ast-add-import-cjs-named",
    description: "add-import into a .cjs file emits require, not an ESM import",
    file: "mod.cjs",
    source: [
      'const path = require("path");',
      "",
      "function buildPath(name) {",
      '  return path.join("/tmp", name);',
      "}",
      "",
      "module.exports = { buildPath };",
      "",
    ].join("\n"),
    edit: { operation: "add-import", importSpec: '{ join } from "path"' },
    expected: [
      'const path = require("path");',
      'const { join } = require("path");',
      "",
      "function buildPath(name) {",
      '  return path.join("/tmp", name);',
      "}",
      "",
      "module.exports = { buildPath };",
      "",
    ].join("\n"),
    tags: ["add-import", "javascript", "commonjs", "139"],
  },
  {
    id: "ast-add-import-cjs-default",
    description: "a default-form spec becomes a whole-module require in CommonJS",
    file: "cli.cjs",
    source: ["module.exports = function run() {};", ""].join("\n"),
    edit: { operation: "add-import", importSpec: 'fs from "fs"' },
    expected: ['const fs = require("fs");', "module.exports = function run() {};", ""].join("\n"),
    tags: ["add-import", "javascript", "commonjs", "139"],
  },
  {
    id: "ast-add-import-cjs-merge",
    description: "a second binding for an already-required module merges instead of duplicating",
    file: "merge.cjs",
    source: ['const { join } = require("path");', "", "module.exports = {};", ""].join("\n"),
    edit: { operation: "add-import", importSpec: '{ resolve } from "path"' },
    expected: ['const { join, resolve } = require("path");', "", "module.exports = {};", ""].join("\n"),
    tags: ["add-import", "javascript", "commonjs", "139"],
  },
  {
    id: "ast-add-import-mjs-stays-esm",
    description: "add-import into a .mjs file still emits an ESM import statement",
    file: "mod.mjs",
    source: ["export const x = 1;", ""].join("\n"),
    edit: { operation: "add-import", importSpec: '{ join } from "path"' },
    expected: ['import { join } from "path";', "export const x = 1;", ""].join("\n"),
    tags: ["add-import", "javascript", "esm", "139"],
  },
  {
    id: "ast-remove-import-cjs-roundtrip",
    description: "remove-import takes out a require binding and leaves the rest of the destructure",
    file: "remove.cjs",
    source: ['const { join, resolve } = require("path");', "", "module.exports = {};", ""].join("\n"),
    edit: { operation: "remove-import", importSpec: '{ join } from "path"' },
    expected: ['const { resolve } = require("path");', "", "module.exports = {};", ""].join("\n"),
    tags: ["remove-import", "javascript", "commonjs", "139"],
  },
  {
    id: "ast-add-import-js-mixed-refused",
    description: "a JavaScript file mixing require and import refuses rather than guessing a module system",
    file: "mixed.js",
    source: ['const a = require("./a");', 'import b from "./b";', "", "module.exports = { a, b };", ""].join("\n"),
    edit: { operation: "add-import", importSpec: '{ join } from "path"' },
    expectRefusal:
      "no extension, package.json, or in-file signal settles which module system Node will use, and emitting either syntax risks a file that does not load (#139)",
    tags: ["add-import", "javascript", "ambiguity", "139"],
  },
];
